controller:
  ingressClassResource:
    enabled: true

  config:
    auth-url: "https://heimdall.heimdall.svc.cluster.local:4456"
    auth-headers-succeed: "authorization"
    headers: |
      X-Forwarded-Uri: %[baseq]
      X-Forwarded-Method: %[method]
      X-Forwarded-Host: %[req.hdr(host)]
