apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: ${namespace}
spec:
  datasource:
    name: Loki
    type: loki
    url: ${loki_url}
    isDefault: false
    uid: LOKI
    access: proxy
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: 'trace_id\":\"(\w+)\"'
          url: '$${__value.raw}'
          datasourceUid: TEMPO
  instanceSelector:
    matchLabels:
      dashboards: grafana