apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: ${namespace}
spec:
  datasource:
    name: Prometheus
    type: prometheus
    url: ${prometheus_url}
    isDefault: true
    uid: PROMETHEUS
    access: proxy
  instanceSelector:
    matchLabels:
      dashboards: grafana