apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: istio-gw
    istio: ingressgateway
    istio.io/gateway-name: istio-gw
  name: istio-gw-istio
  namespace: istio-gw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-gw-istio
subjects:
  - kind: ServiceAccount
    name: istio-gw-istio