apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: ${namespace}
spec:
  dnsNames:
    - "minio.monitoring"
    - "minio.monitoring.svc"
    - "minio.monitoring.svc.cluster.local"
    - "*.minio.monitoring.svc.cluster.local"
    - '*.minio-hl.monitoring.svc.cluster.local'
  secretName: minio-tls
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
