apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-tls
  namespace: ${namespace}
spec:
  dnsNames:
    - echo-app
    - echo-app.default
    - echo-app.default.svc
    - echo-app.default.svc.cluster.local
    - echo-app.local
  ipAddresses:
    - 172.18.255.200
  secretName: eg-tls
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: ${namespace}
#  annotations:
#    cert-manager.io/cluster-issuer: root-ca
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      hostname: echo-app.local
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: eg-tls
            kind: Secret
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ext-auth-heimdall
  namespace: ${namespace}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  extAuth:
    grpc:
      backendRefs:
        - name: heimdall
          port: 4456
          namespace: heimdall
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-app
  namespace: ${namespace}
spec:
  parentRefs:
    - name: eg
      namespace: ${namespace}
  hostnames:
    - "echo-app.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: echo-app
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /