%{ if global_integration_enabled }
%{ if gateway_api_enabled }
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-app
  namespace: ${namespace}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: ingress
  hostnames:
    - "echo-app.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: echo-app
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
%{ else }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: echo-app
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - echo-app.local
      secretName: echo-app
  rules:
    - host: echo-app.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo-app
                port:
                  number: 8080
---
%{ endif }
---
%{ else }
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo-app
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: echo-app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`echo-app.local`) && PathPrefix(`/`)
      middlewares:
        - name: heimdall
          namespace: heimdall
      services:
        - kind: Service
          name: echo-app
          namespace: ${namespace}
          port: app-port
  tls:
    secretName: echo-app
---
%{ endif }