apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-tls
  namespace: ${namespace}
spec:
  secretTemplate:
    name: sts-tls
  secretName: sts-tls
  dnsNames:
    - sts
    - sts.minio-operator.svc
    - sts.minio-operator.svc.cluster.local
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer