apiVersion: v1
kind: Service
metadata:
  name: echo-app
  namespace: ${namespace}
spec:
  ports:
    - name: app-port
      port: 8080
      targetPort: http-port
  selector:
    app.kubernetes.io/name: echo-app
