baseURL: https://dadrus.github.io/
languageCode: en-us
title: Heimdall
theme: mytheme
relativeURLS: true
sectionPagesMenu: main
enableGitInfo: true

security:
  enableInlineShortcodes: false
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  funcs:
    getenv: ['^HUGO_']

  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']

markup:
  asciidocExt:
    extensions: ['asciidoctor-diagram', 'asciidoctor-html5s']
    backend: html5
    trace: true
    verbose: true
    workingFolderCurrent: true
    attributes:
      source-highlighter: rouge
      rouge-css: style
      rouge-style: monokai.sublime
      icons: font

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
    - rss
    - json
  section:
    - html
    - rss
    - json

menu:
  main:
    - identifier: docs
      title: Docs
      url: docs/welcome
      weight: 100

    - identifier: get_started
      title: Get Started
      weight: 300

    - identifier: guides
      title: Integration Guides
      weight: 400

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - ':fileModTime'
    - ':default'

params:
  copyright: 2022-2023 Â© Heimdall Project Authors. All rights reserved.
  version: x-current-version
  license:
    name: Apache 2.0
    url: https://github.com/dadrus/heimdall/blob/master/LICENSE
  author: Dimitrij Drus
  description: An open source Identity Aware Proxy and an Access Control Decision service for cloud native applications
  github:
    user: dadrus
    project: heimdall
  community:
    title: Discord
    url: https://discord.gg/qQgg8xKuyb
  version_file: /heimdall/data.json
  search_index_file: /heimdall/x-current-version/index.json
  path_prefix: /heimdall/x-current-version
  docs_entry_point: /docs/welcome.adoc

module:
  mounts:
    - source: versions
      target: static
    - source: openapi
      target: static
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.js
      target: assets/js/bootstrap.bundle.js
    - source: node_modules/bootstrap-icons/font/fonts
      target: static/css/fonts
